### ISSUE TITLE
integration of discovery

### ISSUE THREAD

**Issue by thiesschneider** [dockur/samba#32]
I think it would be great to have the option to make the smb share discoverable in my network. Is it possible to install wsdd to the image?
Perhaps enable and disable it via environment variable?

**Comment by JBlond** [comment]
A repo for that would be https://github.com/christgau/wsdd

**Comment by pifou25** [comment]
Using another docker image for this purpose, the following docker-compose stack works, with a `.env` file for every variables:
```
services:
  samba:
    image: dockurr/samba
    container_name: samba
    network_mode: bridge
    environment:
      NAME: "${NAME}"
      USER: "${USER}"
      PASS: "${PASS}"
    ports:
      - 445:445
    volumes:
      - /media/samba:/storage
    restart: unless-stopped

  wsdd:
    image: "kosdk/wsdd"
    environment:
      - HOST_NAME="${HOST_NAME}"
      - WORKGROUP="${WORKGROUP}"
    restart: unless-stopped
    network_mode: "host"
```
