### ISSUE TITLE
Non-link-based multiple mount folders

### ISSUE THREAD

**Issue by nan-mu** [dockur/samba#35]
I wonder if it's possible to display multiple folders at the \\\\\<ip\>\\<folder level\>? I need to expose multiple folder directories on my host, but it seems like I have to use  \\\\\<ip\>\\main_folder and then link multiple directories within this main folder. Is there some magic in the custom configuration files?

**Comment by HanLiQL** [comment]
直接在搜索里输入\\<ip>就能显示你在smb.conf设置的所有的文件夹，但是好像不能通过映射网络驱动或添加一个网络位置实现这样的功能，这两个功能好像必须绑定在一个具体的文件夹上。
可能你需要在文件系统那一端做好这样的映射。有什么更具体的需求可以一起想想办法。

**Comment by nan-mu** [comment]
啊，春节快乐，然后我找到了符合我希望的做法，就是去写配置文件：
```yaml
services:
  samba:
    image: dockurr/samba
    container_name: samba
    networks:
      - samba
    ports:
      - 445:445
    volumes:
      - ./dir1:/dir1 # 挂载1目录
      - ./smb.conf:/etc/samba/smb.conf # 映射文件夹主要配置
      - ./users.conf:/etc/samba/users.conf # 多用户管理
      - /dir2:/dir2 # 挂载2目录

networks:
  samba:
    name: samba
```

```conf
[global]
        server string = samba
        idmap config * : range = 3000-7999
        security = user
        server min protocol = SMB2

        # disable printing services
        load printers = no
        printing = bsd
        printcap name = /dev/null
        disable spoolss = yes

[dir1]
        path = /dir1
        comment = dir1
        valid users = @smb
        browseable = yes
        writable = yes
        read only = no
        force user = root
        force group = root

[dir2]
        path = /dir2
        comment = dir2
        valid users = @smb
        browseable = yes
        writable = yes
        read only = no
        force user = root
        force group = root
```

我必须承认我在这类历史悠久的工具上了解不多，看起来在那个时代他们已经做的很完善了。这是在windows下工作的样子。目前没有遇到什么问题。

![Image](https://github.com/user-attachments/assets/b90070b6-8d94-4bef-a280-286308668e60)
