### ISSUE TITLE
smb.conf mounts as a directory instead of a file

### ISSUE THREAD

**Issue by Hash6232** [dockur/samba#38]
As the title says, when I try to use the settings found in the docs I don't get the expected results
```yaml
volumes:
  - /example/smb.conf:/etc/samba/smb.conf

```
My docker compose:
```yaml
services:
  samba:
    image: dockurr/samba
    container_name: samba
    ports:
      - 446:445
    volumes:
      - /srv/docker/samba/smb.conf:/etc/samba/smb.conf

```

And when I try to directly mount the `/etc/samba` directory the container exits with the following error:
```
cp: can't stat '/etc/samba/smb.default': No such file or directory
```

`/srv/docker` is owned by root, `/srv/docker/samba` is owned by a user.
