### ISSUE TITLE
new samba install with custom /etc/samba/smb.conf failing to start with copy error of smb.conf to /etc/samba/smb.conf

### ISSUE THREAD

**Issue by karpana** [dockur/samba#4]
when I assemble my docker-compose file, as follows, the server starts up, but has the "default" configuration (as outlined in the https://github.com/dockur/samba/blob/master/smb.conf file).

```yml
    samba:
      container_name: samba
      image: dockurr/samba
      environment:
        USER: "user"
        PASS: "pass"
        UID: 7057    # Optional, default 1000
        GID: 8000    # Optional, default 1000
        RW: true     # Optional, default true
        TZ: "America/Winnipeg"
      ports:
        - 445:445
      volumes:
        - '/docker_persistent_storage/samba/storage:/storage'
      logging:
        driver: json-file
        options:
          max-size: 10m
      networks:
        - samba
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      restart: always
```

I can confirm I can browse to the exposed `data` share, and read and write files.

When I try to override the smb.conf file by adding the following line into the volumes section, as indicated by the FAQ entry in the README.md file, samba won't start and all I get is a bunch of "copy errors" when I view the docker logs, and the docker container never comes online

```yml
- '/docker_persistent_storage/samba/conf/smb.conf:/etc/samba/smb.conf:ro'
```

```
Added user user.
sed: can't move '/etc/samba/smb.confEnAfCH' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confhPGpIO' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confBMKoie' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confkpNbgm' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confHDfpCd' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confnJaLNF' to '/etc/samba/smb.conf': Resource busy
chgrp: /etc/samba/smb.conf: Read-only file system
chown: /etc/samba/smb.conf: Read-only file system
sed: can't move '/etc/samba/smb.confJliKBI' to '/etc/samba/smb.conf': Resource busy
```

Please help me understand how I can override the smb.conf file.
